src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
if (env('APP_ENV') === 'production') {
    URL::forceSchema('https');
}
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', function () {
        return view('dashboard');
    })->name('root');
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
    Route::get('/settings', function () {
        return view('setting');
    });
    Route::get('/reviews', function () {
        return view('review');
    });
    Route::get('/bad-reviews', function () {
        return view('bad_review');
    });
    Route::get('profile', function () {
        return view('profile');
    })->name('profile');

    Route::get('customers', function () {
        return view('customer');
    })->name('customers');

    Route::get('templates', function () {
        return view('template');
    })->name('templates');

    Route::get('feedback',function(){
        return view('feedback');
    })->name('feedback');

    Route::get('sender',function(){
        return view('sender');
    })->name('sender');

    Route::get('recipient',function(){
        return view('recipient');
    })->name('recipient');

    Route::get('shipments',function(){
        return view('shipments');
    })->name('shipments');

    Route::get('shipments/create',function(){
        return view('shipments-create');
    })->name('shipments.create');

    Route::get('shipments/edit',function(){
        return view('shipments-edit');
    })->name('shipments.edit');

    Route::get('commodities',function(){
        return view('commodities');
    })->name('commodities');

    Route::get('commodities/categories',function(){
        return view('commodities-categories');
    })->name('commodities.categories');

    Route::get('commodities/brand',function(){
        return view('commodities-brand');
    })->name('commodities.brand');

    Route::get('commodities/charges',function(){
        return view('commodities-charges');
    })->name('commodities.charges');

    Route::get('export-list',function(){
        return view('export-list');
    })->name('export-list');

    Route::get('export-list/create',function(){
        return view('export-list-create');
    })->name('export-list.create');

    Route::get('export-list/scan',function(){
        return view('export-list-scan');
    })->name('export-list.scan');

    Route::get('export-list/export-awb',function(){
        return view('export-awb');
    })->name('export-list.export_awb');

    Route::get('export-list/edit',function(){
        return view('export-list-edit');
    })->name('export-list.edit');

    Route::get('export-list/import',function(){
        return view('import-export-list');
    })->name('export-list.import');

    Route::get('export-list/import-list',function(){
        return view('import-list');
    })->name('export-list.import-list');

    Route::get('tracking-list',function(){
        return view('tracking');
    })->name('tracking.tracking-list');
    
    Route::get('consolidated-tracking-list',function(){
        return view('consolidated_tracking_list');
    })->name('tracking.consolidated-tracking-list');

    Route::get('tracking/scan',function(){
        return view('scan_tracking');
    })->name('tracking.scan-tracking');

    Route::get('tracking/consolidated-tracking',function(){
        return view('consolidated_tracking');
    })->name('tracking.consolidated-tracking');
});

    Route::get('request-customer-list',function(){
        return view('request-customer-list');
    })->name('request-customer-list');
    
    Route::get('check-shipment',function(){
        return view('check_shipments');
    })->name('check-shipment');

    Route::get('request-label-list',function(){
        return view('request-label-list');
    })->name('request-label-list');

    Route::get('request-label-package-list',function(){
        return view('request-label-package');
    })->name('request-label-package-list');

//Route::get('/check-shipments/pagination', 'CheckShipmentsAPIController@pagination')->name('checkShipments.pagination');
/*
 /--------------------------------------------------------------------
 / Route admin
 /--------------------------------------------------------------------
 */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::get('/', function () {
        return view('admin.dashboard');
    })->name('root');

    Route::get('/dashboard-agent', function () {
        return view('admin.dashboard_agent');
    })->name('root_agent');

    Route::get('dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');

    Route::get('access-user/{userId}/{redirectTo?}', 'DashboardController@accessUser');

    Route::get('users', function () {
        return view('admin.users');
    })->name('users');

    Route::get('notices', function () {
        return view('admin.notices');
    })->name('notices');

    Route::get('manage-background', function () {
        return view('admin.manage_background');
    })->name('manage_background');

    Route::get('settings',function(){
        return view('admin.settings');
    })->name('settings');

    Route::get('shipment-status',function(){
        return view('admin.shipment_status');
    })->name('shipment_status');

    Route::get('service-type-zone',function(){
        return view('admin.service_type_zone');
    })->name('service_type_zone');

    Route::get('city',function(){
        return view('admin.city');
    })->name('city');

    Route::get('awb-air',function(){
        return view('admin.awb_air');
    })->name('awb-air');

    Route::get('request-label-list',function(){
        return view('admin.request_label_list');
    })->name('request-label-list');

    Route::get('setting-general',function(){
        return view('admin.setting_general');
    })->name('setting_general');

});
Route::get('request-label',function(){
    return view('request-label');
})->name('request-label');

Route::get('request-customer',function(){
    return view('request-customer');
})->name('request-customer');

Route::get('check-export-list',function(){
    return view('check-export-list');
})->name('check-export-list');

Route::get('check-exportlist',function(){
    return view('check-export-list-2');
})->name('check-export-list-2');

Route::get('customer-login',function(){
    return view('customer-login');
})->name('customer-login');

Route::get('callback/facebook/{store}/{provider}', 'CallbackController@facebookCallback')->name('callback.facebook');
Route::post(
    'stripe/webhook',
    '\App\Http\Controllers\StripeWebhookController@handleWebhook'
);
Route::get('/review/{shortId}/{step?}', 'ReviewRedirectController@index')->name('review.redirect');
Route::post('/review/{shortId}/{step?}', 'ReviewRedirectController@submit')->name('review.redirect.submit');
Route::get('/register-thanks', function () {
    return view('auth.register_thanks');
});
Route::get('/get-reviews-api', 'ApiGetReviews@get')->name('data.reviews');
Route::get('/get-reviews-detail-api', 'ApiGetReviews@detail')->name('data.detail.reviews');
Route::get('/{slug}', 'ReviewRedirectController@redirectByStoreSlug')->name('review.redirect.slug');
Route::get('/{slug}/{id}', 'ReviewRedirectController@redirectByStoreSlug')->name('review.redirect.slug.id');
Route::get('/storage-link', function() {
	echo Artisan::call("storage:link");
});

src/resources/views/layouts/admin/header.blade.php
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
  <!-- BEGIN HEADER INNER -->
  <div class="page-header-inner ">
    <!-- BEGIN LOGO -->
    <div class="page-logo">
      <a href="{!! route('admin.root') !!}">
        <img src="../assets/layouts/layout4/img/logo-blue.png" alt="logo" class="logo-default"/></a>

      <div class="menu-toggler sidebar-toggler">
        <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
      </div>
    </div>
    <!-- END LOGO -->
    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse"
       data-target=".navbar-collapse"> </a>
    <!-- END RESPONSIVE MENU TOGGLER -->
    <!-- BEGIN PAGE ACTIONS -->
    <!-- DOC: Remove "hide" class to enable the page header actions -->
    
    <!-- END PAGE ACTIONS -->
    <!-- BEGIN PAGE TOP -->
    <div class="page-top">
      <!-- BEGIN HEADER SEARCH BOX -->
      <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
      {{--<form class="search-form" action="page_general_search_2.html" method="GET">--}}
        {{--<div class="input-group">--}}
          {{--<input type="text" class="form-control input-sm" placeholder="Search..." name="query">--}}
                            {{--<span class="input-group-btn">--}}
                                {{--<a href="javascript:;" class="btn submit">--}}
                                  {{--<i class="icon-magnifier"></i>--}}
                                {{--</a>--}}
                            {{--</span>--}}
        {{--</div>--}}
      {{--</form>--}}
      <!-- END HEADER SEARCH BOX -->
      <!-- BEGIN TOP NAVIGATION MENU -->
      <div class="top-menu">
        <ul class="nav navbar-nav pull-right">
          <li class="separator hide"></li>
          <!-- BEGIN NOTIFICATION DROPDOWN -->
          <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
          {{--<li class="dropdown dropdown-extended dropdown-notification dropdown-dark" id="header_notification_bar">--}}
            {{--<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"--}}
               {{--data-close-others="true">--}}
              {{--<i class="icon-bell"></i>--}}
              {{--<span class="badge badge-success"> 7 </span>--}}
            {{--</a>--}}
            {{--<ul class="dropdown-menu">--}}
              {{--<li class="external">--}}
                {{--<h3>--}}
                  {{--<span class="bold">12 pending</span> notifications</h3>--}}
                {{--<a href="page_user_profile_1.html">view all</a>--}}
              {{--</li>--}}
              {{--<li>--}}
                {{--<ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">just now</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-success">--}}
                                                            {{--<i class="fa fa-plus"></i>--}}
                                                        {{--</span> New user registered. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">3 mins</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-danger">--}}
                                                            {{--<i class="fa fa-bolt"></i>--}}
                                                        {{--</span> Server #12 overloaded. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">10 mins</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-warning">--}}
                                                            {{--<i class="fa fa-bell-o"></i>--}}
                                                        {{--</span> Server #2 not responding. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">14 hrs</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-info">--}}
                                                            {{--<i class="fa fa-bullhorn"></i>--}}
                                                        {{--</span> Application error. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">2 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-danger">--}}
                                                            {{--<i class="fa fa-bolt"></i>--}}
                                                        {{--</span> Database overloaded 68%. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">3 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-danger">--}}
                                                            {{--<i class="fa fa-bolt"></i>--}}
                                                        {{--</span> A user IP blocked. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">4 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-warning">--}}
                                                            {{--<i class="fa fa-bell-o"></i>--}}
                                                        {{--</span> Storage Server #4 not responding dfdfdfd. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">5 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-info">--}}
                                                            {{--<i class="fa fa-bullhorn"></i>--}}
                                                        {{--</span> System Error. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                  {{--<li>--}}
                    {{--<a href="javascript:;">--}}
                      {{--<span class="time">9 days</span>--}}
                                                    {{--<span class="details">--}}
                                                        {{--<span class="label label-sm label-icon label-danger">--}}
                                                            {{--<i class="fa fa-bolt"></i>--}}
                                                        {{--</span> Storage server failed. </span>--}}
                    {{--</a>--}}
                  {{--</li>--}}
                {{--</ul>--}}
              {{--</li>--}}
            {{--</ul>--}}
          {{--</li>--}}
          <!-- END NOTIFICATION DROPDOWN -->
          <li class="separator hide"></li>
          <!-- BEGIN USER LOGIN DROPDOWN -->
          <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
          <li class="dropdown dropdown-user dropdown-dark">
            <a href="javascript:;" class="dropdown-toggle hidden-xs" data-toggle="dropdown" data-hover="dropdown"
               data-close-others="true">
              <span class="username username-hide-on-mobile"> {{ Auth::user()->full_name }} </span>
              <!-- DOC: Do not remove below empty space(&nbsp;) as its purposely used -->
              <img alt="" class="img-circle" src="../assets/layouts/layout4/img/avatar.png"/> </a>
            <ul class="dropdown-menu dropdown-menu-default">
              <li>
                <a href="{!! url('/') !!}">
                  <i class="icon-user"></i> Application Panel </a>
              </li> 
              <li class="divider"></li>
              <li>
                <a href="{!! url('/logout') !!}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                  <i class="icon-key"></i> Log Out </a>

                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                </form>
              </li>
            </ul>
          </li>
          <!-- END USER LOGIN DROPDOWN -->
        </ul>
      </div>
      <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END PAGE TOP -->
  </div>
  <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

src/resources/views/layouts/admin/menu.blade.php
<?php if(Auth::user()->role == 1) { ?>


<li class="{!! Request::is('admin/users') ? 'active' : '' !!} sidebar-customer">
    <a href="{!! url('admin/users') !!}" class="nav-link nav-toggle">
        <i class="icon-users"></i>
        <span class="title">Users Account</span>
    </a>
</li>

<li class="{!! Request::is('admin/service-type-zone') ? 'active' : '' !!} sidebar-customer">
    <a href="{!! url('admin/service-type-zone') !!}" class="nav-link nav-toggle">
        <i class="icon-list"></i>
        <span class="title">Service Type Zone</span>
    </a>
</li>
<li class="{!! Request::is('admin/city') ? 'active' : '' !!} sidebar-customer">
    <a href="{!! url('admin/city') !!}" class="nav-link nav-toggle">
        <i class="icon-list" ></i>
        <span class="title">City</span>
    </a>
</li>
<li class="{!! Request::is('admin/awb-air') ? 'active' : '' !!} sidebar-customer">
    <a href="{!! url('admin/awb-air') !!}" class="nav-link nav-toggle">
        <i class="icon-plane" ></i>
        <span class="title">Awb Air</span>
    </a>
</li>

<li data-toggle="collapse" data-target="#shipments" class="{!! (Request::is('shipments*') || Request::is('recipients*')) ? 'active' : '' !!} sidebar-customer" id="menu-3">
    <a href="#" class="nav-link nav-toggle">
        <i class="icon-bag"></i>
        <span class="title">Shipments</span>
        <span class="fa {!! Request::is('shipments*') ? 'fa-angle-down' : 'fa-angle-left' !!}"></span>
    </a>
</li>
<ul class="collapse sub-menu {!! (Request::is('shipments*') || Request::is('shipments*')) ? 'in' : '' !!}" id="shipments">
    <li class="{!! Request::is('admin/shipment-status') ? 'active' : '' !!} sidebar-customer">
        <a href="{!! url('admin/shipment-status') !!}" class="nav-link nav-toggle">
            <i class="icon-users"></i>
            <span class="title">Shipment Status</span>
        </a>
    </li>
</ul>
<li data-toggle="collapse" data-target="#commodities" class="{!! (Request::is('commodities*') || Request::is('commodities*')) ? 'active' : '' !!} sidebar-customer" id="menu-5">
    <!-- <a href="{!! url('/commodities') !!}" class="nav-link nav-toggle"> -->
    <a href="#" class="nav-link nav-toggle">
        <i class="icon-layers"></i>
        <span class="title">Commodities</span>
        <span class="fa {!! Request::is('commodities*') ? 'fa-angle-down' : 'fa-angle-left' !!}"></span>
    </a>
</li>
<ul class="collapse sub-menu {!! (Request::is('commodities*') || Request::is('commodities*')) ? 'in' : '' !!}" id="commodities">
    <li class="{!! Request::is('commodities/brand*') ? 'active' : '' !!} sidebar-customer" id="menu-5-3">
        <a href="{!! url('/commodities/brand') !!}" class="nav-link nav-toggle sub-active-custom">
            <i class="fa fa-bolt"></i>
            <span class="title">Brand</span>
        </a>
    </li>
    <li class="{!! Request::is('commodities/categories*') ? 'active' : '' !!} sidebar-customer" id="menu-5-4">
        <a href="{!! url('/commodities/categories') !!}" class="nav-link nav-toggle sub-active-custom">
            <i class="fa fa-bolt"></i>
            <span class="title">Categories</span>
        </a>
    </li>
</ul>
<li class="{!! Request::is('admin/request-label-list') ? 'active' : '' !!} sidebar-customer">
    <a href="{!! url('admin/request-label-list') !!}" class="nav-link nav-toggle">
        <i class="icon-list" ></i>
        <span class="title">Request Label</span>
    </a>
</li>
<li data-toggle="collapse" data-target="#setting_config" class="{!! (Request::is('setting-general*') || Request::is('setting-general*')) ? 'active' : '' !!} sidebar-customer" id="menu-3">
    <a href="{!! url('admin/setting-general') !!}" class="nav-link nav-toggle">
        <i class="icon-settings"></i>
        <span class="title">Setting General</span>
    </a>
</li>

<?php } ?>

src/resources/views/layouts/admin/sidebar.blade.php
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
        <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
        <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
        <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <ul class="page-sidebar-menu   " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            @include('layouts.admin.menu')

        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->